core/urls.py
from django.urls import path
import core.views

app_name = 'core'

urlpatterns = [
    path('', core.views.Index.as_view(), name='index'),
    path('price/', core.views.Price.as_view(), name='price'),
    path('info/', core.views.Info.as_view(), name='info'),
    path('books/', core.views.Books.as_view(), name='book_list'),
    path('books/<int:pk>/', core.views.BookDetail.as_view(), name='book_detail'),
    path('books/create/', core.views.BookCreate.as_view(), name='book_create'),
    path('books/<int:pk>/update/', core.views.BookUpdate.as_view(), name='book_update'),
    path('books/<int:pk>/delete/', core.views.BookDelete.as_view(), name='book_delete'),
]

project/urls.py
import os

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static('node_modules', document_root=os.path.join(settings.BASE_DIR, 'node_modules'))

core/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField('Имя автора', max_length=128)

    def __str__(self):
        return self.name


class Genre(models.Model):
    name = models.CharField('Название жанра', max_length=64)

    def __str__(self):
        return self.name


class Book(models.Model):
    author = models.ForeignKey('core.Author', on_delete=models.CASCADE, null=True, blank=True, related_name='books')
    name = models.CharField('Название', max_length=128)
    pages = models.IntegerField('Количество страниц', blank=True, null=True)
    genre = models.ForeignKey('core.Genre', on_delete=models.CASCADE, null=True, blank=True, related_name='books')

    class Meta:
        ordering = ['pages']
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'

    def __str__(self):
        return self.name


class Order(models.Model):
    date = models.DateField()
    book = models.ManyToManyField('core.Book')

core/forms.py
from django import forms

import core.models


class BookSearch(forms.Form):
    name = forms.CharField(label='Название', required=False)
    author = forms.ModelChoiceField(label='Автор книги', queryset=core.models.Author.objects.all(), required=False)
    genre = forms.ModelChoiceField(label='Жанр книги', queryset=core.models.Genre.objects.all(), required=False)


class BookEdit(forms.ModelForm):
    class Meta:
        model = core.models.Book
        fields = '__all__'

core/views.py
from django.urls import reverse
from django.views.generic import TemplateView, ListView, DetailView, UpdateView, CreateView, DeleteView

import core.models
import core.forms
import core.filters


class TitleMixin:
    title: str = None

    def get_title(self):
        return self.title

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['title'] = self.get_title()
        return context


class Bin(TitleMixin, TemplateView):
    template_name = 'core/bin.html'
    title = 'Главная'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['info'] = self.get_info()
        return context

    def get_info(self):
        return 'Главная страница'


class Index(TitleMixin, TemplateView):
    template_name = 'core/index.html'
    title = 'Главная страница'


class Price(TitleMixin, TemplateView):
    template_name = 'core/price.html'
    title = 'Прайс'


class Info(TitleMixin, TemplateView):
    template_name = 'core/info.html'
    title = 'Информация'


class Books(TitleMixin, ListView):
    title = 'Книги'

    def get_filters(self):
        return core.filters.BookFilter(self.request.GET)

    def get_queryset(self):
        return self.get_filters().qs

    def get_context_data(self):
        context = super().get_context_data()
        context['form'] = core.forms.BookSearch(self.request.GET or None)
        return context


class BookDetail(TitleMixin, DetailView):
    queryset = core.models.Book.objects.all()

    def get_title(self):
        return str(self.get_object())


class BookUpdate(TitleMixin, UpdateView):
    model = core.models.Book
    form_class = core.forms.BookEdit

    def get_title(self):
        return f'Изменение данных о книге"{str(self.get_object())}"'

    def get_success_url(self):
        return reverse('core:book_list')


class BookCreate(TitleMixin, CreateView):
    model = core.models.Book

    form_class = core.forms.BookEdit
    title = 'Добавление книги'

    def get_success_url(self):
        return reverse('core:book_list')


class BookDelete(TitleMixin, DeleteView):
    model = core.models.Book

    def get_title(self):
        return f'Удаление книги{str(self.get_object())}'

    def get_success_url(self):
        return reverse('core:book_list')

ansible/templates/nginx.jinja2
server {
    listen 80;
    server_name default;

    access_log  /var/log/www/django_test4/access.log;
    error_log   /var/log/www/django_test4/error.log;

    location /node_modules {
        alias /var/www/django_test4/static/node_modules;
    }

    location /static {
        alias /var/www/django_test4/static;
    }

    location / {
        proxy_pass http://127.0.0.1:8854/;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
    }
}

core/templates/core/bin.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet">

    <title>{{ title }}</title>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'core:index' %}">Книжный</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                  <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Главная</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="/admin/">Администрирование</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'core:book_list' %}">Книги</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'core:price' %}">Прайс</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'core:info' %}">Информация</a>
                  </li>
              </ul>
          </div>
      </div>
  </nav>


{% block title %}
    {% if title %}
        <h3 style="margin-bottom: 40px">{{ title }}</h3>
    {% endif %}
{% endblock %}

{% block content %}
{% endblock %}

    <script src="/node_modules/bootstrap/dist/js/bootstrap.bundle.js"> </script>
  </body>
</html>

core/templates/core/book_confirm_delete.html
{% extends 'core/bin.html' %}
{% load bootstrap5 %}

{% block content %}
    <div class="alert alert-danger">
        Вы действительно хотите удалить книгу "{{ object }}"
    </div>

    <form method="post">{% csrf_token %}
        <button type="submit" class="btn btn-danger">
            Да
        </button>
        <a href="{% url 'core:book_list' %}" class="btn btn-success"> Нет</a>
    </form>
{% endblock %}

core/templates/core/book_detail.html
{% extends 'core/bin.html' %}
{% block content %}
    <div class="alert alert-primary" role="alert">
    Автор книги:
    <td>{{ book.author.name|default:'Неизвестно' }}</td>
    </div>
    <a href="{% url 'core:book_update' object.pk %}">Изменить</a>
    <a href="{% url 'core:book_delete' object.pk %}">Удалить</a>
{% endblock %}

core/templates/core/book_form.html
{% extends 'core/bin.html' %}
{% load bootstrap5 %}

{% block content %}

<form class="row g-3" method="post" style="margin-top: 10px">{% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <div class="col-auto">
        <button type="submit" class="btn btn-primary mb-3">Сохранить</button>
    </div>
</form>

{% endblock %}

core/templates/core/book_list.html
{% extends 'core/bin.html' %}

{% block content %}
    {% include 'core/search_books_include.html' %}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название</th>
            <th scope="col">Количество страниц</th>
            <th scope="col">Имя автора</th>
            <th scope="col">Жанр</th>
        </tr>
        </thead>
        <tbody>
        {% for book in object_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'core:book_detail' book.pk %}">{{ book.name|capfirst }}</a></td>
                <td>{{ book.pages|default:" - " }}</td>
                <td>{{ book.author.name|default:" - " }}</td>
                <td>{{ book.genre.name|default:" - " }}</td>
            </tr>
        {% empty %}
            <h4>Не найдено</h4>
        {% endfor %}
        </tbody>
    </table>

    <a href="{% url 'core:book_create' %}" class="btn btn-success"> Добавить книгу</a>

{% endblock %}

core/templates/core/index.html
{% extends 'core/bin.html' %}
{% load bootstrap5 %}
{% load static %}

{% block content %}

    <center><h4>Это лучшие книги по мнению нашей команды</h4></center>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col">
            <div class="card h-100">
                <img src="{% static 'core/img/book1.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Liz❤️‍🔥chka</h5>
                    <p class="card-text">Данная книга о том, как жизнерадостная девушка встретила клоуна. Жанр: хоррор.</p>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card h-100">
                <img src="{% static 'core/img/book2.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Maxim</h5>
                    <p class="card-text">Он был обычным работником "Магнита", пока в его жизни... Жанр: боевик</p>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card h-100">
                <img src="{% static 'core/img/book3.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">German</h5>
                    <p class="card-text">Он думал, что жизнь это трагедия, а оказалось романтика. Жанр: романтика.</p>
                </div>
            </div>
        </div>
    </div>

    <center><h4>Это лучшие авторы по мнению нашей команды</h4></center>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col">
            <div class="card h-100">
                <img src="{% static 'core/img/author1.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Deniska</h5>
                    <p class="card-text">Автор Deniska автор мировых хитов с большим именем в мировой индустрии.</p>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card h-100">
                <img src="{% static 'core/img/author2.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Vladik</h5>
                    <p class="card-text">Биография этого автора загадочна и туманна, как и его детективы.</p>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card h-100">
                <img src="{% static 'core/img/author3.jpeg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Pushkin</h5>
                    <p class="card-text">Умер в перестрелке.</p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

core/templates/core/info.html
{% extends 'core/bin.html' %}
{% block content %}
    <center><h5>По вопросам, предложениям сотрудничества контакты</h5></center>
    <table class="table">
        <tbody>
        <tr>
            <td>Телефонный номер:</td>
            <td>+79378427880</td>
        </tr>
        <tr>
            <td>mail:</td>
            <td>nugaev.vlad@mail.ru</td>
        </tr>
        </tbody>
    </table>
{% endblock %}

core/templates/core/price.html
{% extends 'core/bin.html' %}
{% load bootstrap5 %}

{% block content %}
<h4>Прайс лист</h4>
    <center>У каждого автора свои ценники за страницу</center>
    <div class="accordion accordion-flush" id="accordionFlushExample">
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingOne">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                    Puskin
                </button>
            </h2>
            <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">У автора Pushkin прайс:За одну страницу вы платите 2 рубля</div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingTwo">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                    Adelina
                </button>
            </h2>
            <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">У автора Adelina вы платите за каждую страницу 5 рублей</div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                    Olga
                </button>
            </h2>
            <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">У автора Olga прайс за любую книгу один: 700 рублей</div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingFour">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseFour" aria-expanded="false" aria-controls="flush-collapseFour">
                    Vladik
                </button>
            </h2>
            <div id="flush-collapseFour" class="accordion-collapse collapse" aria-labelledby="flush-headingFour" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">У автора Vladik прайс такой,что за одну страницу ты платишь 3 рубля,но если в книге больше 100 страниц,то ты платишь за страницу 50 копеек</div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingFive">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseFive" aria-expanded="false" aria-controls="flush-collapseive">
                    Deniska
                </button>
            </h2>
            <div id="flush-collapseFive" class="accordion-collapse collapse" aria-labelledby="flush-headingFive" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">Автор Deniska дарит свои книги бесплатно.</div>
            </div>
        </div>
    </div>



{% endblock %}

core/templates/core/search_books_include.html
{% load bootstrap5 %}
<form class="row g-3">
    {% bootstrap_form form layout='horizontal'%}
    <div class="col-auto">
        <button type="submit" class="btn btn-primary">Поиск</button>
    </div>
</form>